/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddChannelMemberRequest
 */
export interface AddChannelMemberRequest {
    /**
     * 
     * @type {number}
     * @memberof AddChannelMemberRequest
     */
    userId: number;
}

/**
 * Check if a given object implements the AddChannelMemberRequest interface.
 */
export function instanceOfAddChannelMemberRequest(value: object): value is AddChannelMemberRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function AddChannelMemberRequestFromJSON(json: any): AddChannelMemberRequest {
    return AddChannelMemberRequestFromJSONTyped(json, false);
}

export function AddChannelMemberRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddChannelMemberRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
    };
}

export function AddChannelMemberRequestToJSON(json: any): AddChannelMemberRequest {
    return AddChannelMemberRequestToJSONTyped(json, false);
}

export function AddChannelMemberRequestToJSONTyped(value?: AddChannelMemberRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
    };
}

