/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OAuthLoginRequest
 */
export interface OAuthLoginRequest {
    /**
     * 
     * @type {string}
     * @memberof OAuthLoginRequest
     */
    accessToken?: string;
}

/**
 * Check if a given object implements the OAuthLoginRequest interface.
 */
export function instanceOfOAuthLoginRequest(value: object): value is OAuthLoginRequest {
    return true;
}

export function OAuthLoginRequestFromJSON(json: any): OAuthLoginRequest {
    return OAuthLoginRequestFromJSONTyped(json, false);
}

export function OAuthLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuthLoginRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
    };
}

export function OAuthLoginRequestToJSON(json: any): OAuthLoginRequest {
    return OAuthLoginRequestToJSONTyped(json, false);
}

export function OAuthLoginRequestToJSONTyped(value?: OAuthLoginRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessToken': value['accessToken'],
    };
}

