/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatMessageDTO
 */
export interface ChatMessageDTO {
    /**
     * 
     * @type {number}
     * @memberof ChatMessageDTO
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof ChatMessageDTO
     */
    channelId?: number;
    /**
     * 
     * @type {number}
     * @memberof ChatMessageDTO
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof ChatMessageDTO
     */
    userName?: string;
    /**
     * 
     * @type {Date}
     * @memberof ChatMessageDTO
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ChatMessageDTO
     */
    modifiedAt?: Date;
    /**
     * 
     * @type {any}
     * @memberof ChatMessageDTO
     */
    message?: any | null;
}

/**
 * Check if a given object implements the ChatMessageDTO interface.
 */
export function instanceOfChatMessageDTO(value: object): value is ChatMessageDTO {
    return true;
}

export function ChatMessageDTOFromJSON(json: any): ChatMessageDTO {
    return ChatMessageDTOFromJSONTyped(json, false);
}

export function ChatMessageDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatMessageDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'channelId': json['channelId'] == null ? undefined : json['channelId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'modifiedAt': json['modifiedAt'] == null ? undefined : (new Date(json['modifiedAt'])),
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ChatMessageDTOToJSON(json: any): ChatMessageDTO {
    return ChatMessageDTOToJSONTyped(json, false);
}

export function ChatMessageDTOToJSONTyped(value?: ChatMessageDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'channelId': value['channelId'],
        'userId': value['userId'],
        'userName': value['userName'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'modifiedAt': value['modifiedAt'] == null ? undefined : ((value['modifiedAt']).toISOString()),
        'message': value['message'],
    };
}

