/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckIn
 */
export interface CheckIn {
    /**
     * 
     * @type {number}
     * @memberof CheckIn
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof CheckIn
     */
    userId?: number;
    /**
     * 
     * @type {number}
     * @memberof CheckIn
     */
    golfCourseId?: number;
    /**
     * 
     * @type {string}
     * @memberof CheckIn
     */
    intent?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckIn
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CheckIn
     */
    openToChat?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof CheckIn
     */
    checkInTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CheckIn
     */
    expiresAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CheckIn
     */
    effectiveExpiration?: Date;
}

/**
 * Check if a given object implements the CheckIn interface.
 */
export function instanceOfCheckIn(value: object): value is CheckIn {
    return true;
}

export function CheckInFromJSON(json: any): CheckIn {
    return CheckInFromJSONTyped(json, false);
}

export function CheckInFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckIn {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'golfCourseId': json['golfCourseId'] == null ? undefined : json['golfCourseId'],
        'intent': json['intent'] == null ? undefined : json['intent'],
        'message': json['message'] == null ? undefined : json['message'],
        'openToChat': json['openToChat'] == null ? undefined : json['openToChat'],
        'checkInTime': json['checkInTime'] == null ? undefined : (new Date(json['checkInTime'])),
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
        'effectiveExpiration': json['effectiveExpiration'] == null ? undefined : (new Date(json['effectiveExpiration'])),
    };
}

export function CheckInToJSON(json: any): CheckIn {
    return CheckInToJSONTyped(json, false);
}

export function CheckInToJSONTyped(value?: CheckIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'golfCourseId': value['golfCourseId'],
        'intent': value['intent'],
        'message': value['message'],
        'openToChat': value['openToChat'],
        'checkInTime': value['checkInTime'] == null ? undefined : ((value['checkInTime']).toISOString()),
        'expiresAt': value['expiresAt'] == null ? undefined : ((value['expiresAt']).toISOString()),
        'effectiveExpiration': value['effectiveExpiration'] == null ? undefined : ((value['effectiveExpiration']).toISOString()),
    };
}

