/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckInRequest
 */
export interface CheckInRequest {
    /**
     * 
     * @type {number}
     * @memberof CheckInRequest
     */
    golfCourseId?: number;
    /**
     * 
     * @type {string}
     * @memberof CheckInRequest
     */
    intent?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckInRequest
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CheckInRequest
     */
    openToChat?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof CheckInRequest
     */
    expiresAt?: Date;
}

/**
 * Check if a given object implements the CheckInRequest interface.
 */
export function instanceOfCheckInRequest(value: object): value is CheckInRequest {
    return true;
}

export function CheckInRequestFromJSON(json: any): CheckInRequest {
    return CheckInRequestFromJSONTyped(json, false);
}

export function CheckInRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckInRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'golfCourseId': json['golfCourseId'] == null ? undefined : json['golfCourseId'],
        'intent': json['intent'] == null ? undefined : json['intent'],
        'message': json['message'] == null ? undefined : json['message'],
        'openToChat': json['openToChat'] == null ? undefined : json['openToChat'],
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
    };
}

export function CheckInRequestToJSON(json: any): CheckInRequest {
    return CheckInRequestToJSONTyped(json, false);
}

export function CheckInRequestToJSONTyped(value?: CheckInRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'golfCourseId': value['golfCourseId'],
        'intent': value['intent'],
        'message': value['message'],
        'openToChat': value['openToChat'],
        'expiresAt': value['expiresAt'] == null ? undefined : ((value['expiresAt']).toISOString()),
    };
}

