/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDMRequest
 */
export interface CreateDMRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateDMRequest
     */
    userIds?: Array<number>;
    /**
     * 
     * @type {any}
     * @memberof CreateDMRequest
     */
    initialMessage?: any | null;
}

/**
 * Check if a given object implements the CreateDMRequest interface.
 */
export function instanceOfCreateDMRequest(value: object): value is CreateDMRequest {
    return true;
}

export function CreateDMRequestFromJSON(json: any): CreateDMRequest {
    return CreateDMRequestFromJSONTyped(json, false);
}

export function CreateDMRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDMRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userIds': json['userIds'] == null ? undefined : json['userIds'],
        'initialMessage': json['initialMessage'] == null ? undefined : json['initialMessage'],
    };
}

export function CreateDMRequestToJSON(json: any): CreateDMRequest {
    return CreateDMRequestToJSONTyped(json, false);
}

export function CreateDMRequestToJSONTyped(value?: CreateDMRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userIds': value['userIds'],
        'initialMessage': value['initialMessage'],
    };
}

