/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GolfCourse
 */
export interface GolfCourse {
    /**
     * 
     * @type {number}
     * @memberof GolfCourse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof GolfCourse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof GolfCourse
     */
    address?: string;
    /**
     * 
     * @type {number}
     * @memberof GolfCourse
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof GolfCourse
     */
    longitude?: number;
    /**
     * 
     * @type {Date}
     * @memberof GolfCourse
     */
    createdAt?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof GolfCourse
     */
    _public?: boolean;
}

/**
 * Check if a given object implements the GolfCourse interface.
 */
export function instanceOfGolfCourse(value: object): value is GolfCourse {
    return true;
}

export function GolfCourseFromJSON(json: any): GolfCourse {
    return GolfCourseFromJSONTyped(json, false);
}

export function GolfCourseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GolfCourse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'address': json['address'] == null ? undefined : json['address'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        '_public': json['public'] == null ? undefined : json['public'],
    };
}

export function GolfCourseToJSON(json: any): GolfCourse {
    return GolfCourseToJSONTyped(json, false);
}

export function GolfCourseToJSONTyped(value?: GolfCourse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'address': value['address'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'public': value['_public'],
    };
}

