FROM openjdk:21-jdk-slim

WORKDIR /app

# Copy gradle wrapper and config first for caching
COPY gradlew .
COPY gradle ./gradle

# Copy build files
COPY build.gradle.kts .
COPY settings.gradle.kts .

# Download dependencies only (speed up rebuilds)
RUN ./gradlew build -x test

# Copy the rest of the source code
COPY . .

# Run the app in dev mode
CMD ["./gradlew", "bootRun"]