FROM node:23.5.0-alpine

WORKDIR /app

# Copy package.json and package-lock.json separately to leverage Docker cache on deps
COPY package.json package-lock.json ./

RUN npm install

# Copy the rest of the source code
COPY . .

# Expose the port your dev server runs on (usually 3000 for React)
EXPOSE 3000

# Start the dev server
CMD ["npm", "run", "dev"]